dep:
	.venv\Scripts\activate
	pip install scikit-learn matplotlib seaborn pandas optimum[onnxruntime-gpu] notebook transformers sentence-transformers[onnx-gpu] datasets jupyter ipywidgets zstandard onnx
	pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124
	pip install peft evaluate
	pip install triton
	# pip install flash-attn --no-build-isolation
